dawn-use-pkg-config.patch: updated to fix:
:: ERROR at //third_party/dawn/src/dawn/native/BUILD.gn:482:18: Duplicate item in list
::     configs += [ ":x11-xcb" ]
::                  ^---------

and the subsequent

:: In file included from ../../third_party/dawn/src/dawn/native/vulkan/VulkanBackend.cpp:20:
:: In file included from ../../third_party/dawn/src/dawn/common/vulkan_platform.h:153:
:: ../../third_party/dawn/src/dawn/common/xlib_with_undefs.h:31:10: fatal error: 'X11/Xlib-xcb.h' file not found
:: #include <X11/Xlib-xcb.h>
::          ^~~~~~~~~~~~~~~~